Logging:
  IncludeScopes: false
  Debug:
    LogLevel:
      Default: Information
      Fortune_Teller_Service: Debug
      Fortune_Teller_UI: Debug
      Steeltoe: Debug
      Pivotal: Debug
  Console:
    LogLevel:
      Default: Information
      Fortune_Teller_Service: Debug
      Fortune_Teller_UI: Debug
      Steeltoe: Debug
      Pivotal: Debug